version: '3'

services:
   nginx:
      image: nginx
      container_name: nginx
      ports:
         - "8000:8000"
         - "443:443"
      working_dir: /var/www/html
      volumes:
         - ./app:/var/www/html
         - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./config/nginx/ngx_conf:/etc/nginx/ngx_conf
      links:
         - php-fpm
   php-fpm:
      image: php:7.3-fpm
      container_name: php-fpm
      ports:
         - "9000:9000"
      working_dir: /var/www/html
      volumes:
         - ./app:/var/www/html
         - ./config/fpm/php.ini:/usr/local/etc/php/php.ini           

